common: &common
  adapter: postgresql
  username: ada
  password: 

development:
  <<: *common
  database: loxopix_dev

test:
  <<: *common
  database: loxopix_test

production:
  <<: *common
  database: loxopix
